<a href="https://colab.research.google.com/github/alexandrecassimiro/VD-com-Python/blob/main/Gr%C3%A1fico_Linha_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import plotly.graph_objs as go
import numpy as np

In [7]:
n = 50 #quantidade de números a serem gerados
x = np.linspace(0,1,n)
random_y1 = np.random.normal(loc =30, scale=2.5, size=n)  #distribuição normal com média 30, desvio padrão 2.5, tamanho n
random_y2 = np.random.randint(low =0, high=50, size=n)    #números aleatórios inteiros entre 0 e 50, amostra 50
random_y3 = np.random.uniform(low =0, high=20, size=n)    #distribuição uniforme entre 0 e 20, amostra 50

In [8]:
x


array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [9]:
random_y1 , random_y2 , random_y3

(array([26.34166288, 24.89031338, 24.88024019, 30.47352463, 34.14114177,
        31.05200577, 29.60092391, 26.17548822, 32.1748696 , 32.29570239,
        30.62744893, 32.78371569, 33.50090999, 33.19031687, 30.57082475,
        32.36287298, 28.31088468, 31.7807927 , 28.20175713, 27.48085026,
        29.511724  , 30.07145572, 27.25747023, 28.57132291, 27.46607654,
        32.00642812, 29.09551012, 25.02743091, 28.26819365, 30.03152033,
        29.65011818, 31.17672969, 34.02508175, 29.0192577 , 28.90206333,
        28.80289001, 32.30173091, 28.14199071, 30.40312647, 30.48733316,
        31.54907308, 26.80878352, 28.79076501, 28.91990456, 30.49292241,
        26.31837074, 25.31204972, 31.03222722, 24.08825478, 28.49397989]),
 array([35, 13, 22, 28, 22, 38, 41, 30, 12, 44, 14,  7, 40, 43, 11, 12,  9,
        45, 25, 42, 13, 18, 44, 19, 23, 37, 11, 27, 33, 33, 33, 31, 20, 47,
         5, 33, 41, 47, 43, 20, 13, 27, 25, 36, 42,  1, 10,  6, 38, 47]),
 array([17.63854653, 12.27997987, 15.88432

In [16]:
linha1 = go.Scatter(
    x=x,
    y=random_y1,
    mode = 'lines',
    name = 'Linha 1'
)
linha2 = go.Scatter(
    x=x,
    y=random_y2,
    mode = 'lines',
    name = 'Linha 2'
)
linha3 = go.Scatter(
    x=x,
    y=random_y3,
    mode = 'lines',
    name = 'Linha 3'
)
data = [linha1, linha2, linha3]
layout = go.Layout(
    title='Minha Figura',
    xaxis=dict(title='Eixo X'), #nomeando eixo X com dicionário
    yaxis=dict(title='Eixo Y')
)
fig = go.Figure(data, layout) #recebendo dados contidos nas linhas e layout do gráfico
fig.show()

In [30]:
#alterando cor, espessura de linhas e agregar pontos

linha1 = go.Scatter(
    x=x,
    y=random_y1,
    mode = 'markers',
    name = 'Linha 1',
    line = dict(color = 'red', width =2)
)
linha2 = go.Scatter(
    x=x,
    y=random_y2,
    mode = 'lines+markers',
    name = 'Linha 2',
    line = dict(color = 'black', width =1)
)
linha3 = go.Scatter(
    x=x,
    y=random_y3,
    mode = 'lines',
    name = 'Linha 3',
    line = dict(color = 'green')
)
data = [linha1, linha2, linha3]
layout = go.Layout(
    title='Minha Figura',
    xaxis=dict(title='Eixo X'), #nomeando eixo X com dicionário
    yaxis=dict(title='Eixo Y')
)
fig = go.Figure(data, layout) #recebendo dados contidos nas linhas e layout do gráfico
fig.show()